### PR TITLE
Boxarts for ScummVM

### PR DESCRIPTION
**Pull request by mrmatteastwood**
I made a fork of the "libretro-thumbnails" repo, then clicked on "upload" and it took me straight to the upload screen without asking me which folder I wanted to upload the files to. Hope this is ok. They need to go into the ScummVM folder's subfolder, "Named_Boxarts".

I noticed that in the ScummVM database, there aren't any named entries for special versions of games, e.g. the CD-ROM or FM-Towns versions of Loom. So I'm not sure whether some of these boxarts will work, perhaps the entries in the ScummVM database need to be renamed?

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks! Added in the repo over at https://github.com/libretro-thumbnails/ScummVM/commit/68d64b6e63fdf458efd9159aa97918612a6c8c89

**Comment by RobLoach** [comment]
Regarding CD-ROM vs FM-Towns, there is some naming issues on the ScummVM database. I would like to see that cleaned up. Unsure of the best way to scrape game info from ScummVM.

**Comment by mrmatteastwood** [comment]
Thanks Rob! I'm not sure how the system works, but I just checked the folders of the different Loom versions and they do have distinct file structures that set them apart.

The EGA version has a whole bunch of .LFL files, while the CD-ROM version only has 5 of them (000.LFL, 901.LFL, 902.LFL, 903.LFL and 904.LFL).

The FM-Towns version can be recognized by the file, loom.exp which none of the others have. Perhaps this helps?

**Comment by RobLoach** [comment]
There use to be a "Grubby ScummVM DAT" that had all the ScummVM files documented, but I'm unsure where it went.

In adopting it to the libretro database, I found some duplicates that were somewhat problematic. But identifying the unique files, like that loom.exp you found, is key :wink:

**Comment by mrmatteastwood** [comment]
Nice! Glad I can help :-)

For the German Full Throttle, the distinguishing file is VOLLGAS.EXE (the English launch executable is throttle.exe).

**Comment by mrmatteastwood** [comment]
Oh, and the EGA Loom does not have the 000/901/902/903/904 LFLs, neither does the FM-Towns.

**Comment by RobLoach** [comment]
Found the DAT project...
https://duckduckgo.com/?q=%22gruby%22+adventurepack+dat+-rommanager

**Pull request closed without merging**
